global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'mssql'
    static_configs:
      - targets: ['mssql:1433']
